# Generated by Django 2.2.16 on 2020-09-17 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.UUIDField()),
                ('case_status', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('competed_on', models.DateField()),
                ('broker_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_broker_id', to=settings.AUTH_USER_MODEL)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_doctor_id', to=settings.AUTH_USER_MODEL)),
                ('lawyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_lawyer_id', to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_patient_id', to=settings.AUTH_USER_MODEL)),
                ('wmg_staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases_wmg_staff_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('recipient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_recipient_id', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sender_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.UUIDField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.CharField(max_length=256)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_case_id', to='home.Cases')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_id', models.UUIDField()),
                ('description', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_case_id', to='home.Cases')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField()),
                ('message', models.CharField(max_length=2048)),
                ('sent_on', models.DateTimeField(auto_now=True)),
                ('conversation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_conversation_id', to='home.Conversation')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=256)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_case_id', to='home.Cases')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_note_id', to='home.Notes')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_schedule_id', to='home.Schedule')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
